# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 00:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TravelBuddyApp', '0003_auto_20160718_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='user',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='Owner', to='TravelBuddyApp.User'),
        ),
    ]
